// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class AllBooksInfo
{
    public string Имя { get; set; }

    public string Isbn { get; set; }

    public int КолВоСтраниц { get; set; }

    public string Название { get; set; }

    public string ЖанроваяГруппа { get; set; }

    public string Автор { get; set; }

    public string ГрупповаяПринадлежностьАвтора { get; set; }

    public string Издательство { get; set; }

    public string Страна { get; set; }

    public string НомерСтеллажа { get; set; }

    public string НомерЗала { get; set; }
}