// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Author
{
    public int AuthorId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string SurName { get; set; }

    public string Group { get; set; }

    public virtual ICollection<BookAuthor> BookAuthors { get; set; } = new List<BookAuthor>();
}