// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Book
{
    public int BookId { get; set; }

    public int PublishingHouseId { get; set; }

    public int RackId { get; set; }

    public int NumberOfPages { get; set; }

    public string AgeRating { get; set; }

    public string Isbn { get; set; }

    public string Name { get; set; }

    public int CodeBook { get; set; }

    public byte[] BookIssued { get; set; }

    public virtual ICollection<BookAuthor> BookAuthors { get; set; } = new List<BookAuthor>();

    public virtual ICollection<BookGenre> BookGenres { get; set; } = new List<BookGenre>();

    public virtual ICollection<BookIssuance> BookIssuances { get; set; } = new List<BookIssuance>();

    public virtual PublishingHouse PublishingHouse { get; set; }

    public virtual Rack Rack { get; set; }
}