// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class DepartmentOfIssuance
{
    public int DepartmentOfOssuanceId { get; set; }

    public string DepartmentNum { get; set; }

    public virtual ICollection<Hall> Halls { get; set; } = new List<Hall>();

    public virtual ICollection<Librarian> Librarians { get; set; } = new List<Librarian>();
}