// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryWin.Models
{
    public partial class getBookPositionResult
    {
        public string Название { get; set; }
        public string Стеллаж { get; set; }
        public string Зал { get; set; }
    }
}
