// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryWin.Models
{
    public partial class getBookInfoResult
    {
        public string Название { get; set; }
        public string ISBN { get; set; }
        [Column("Количество страниц")]
        public int Количествостраниц { get; set; }
        [Column("Возрастной рейтинг")]
        public string Возрастнойрейтинг { get; set; }
        public string Жанр { get; set; }
        [Column("Тип жанра")]
        public string Типжанра { get; set; }
        [Column("Имя автора")]
        public string Имяавтора { get; set; }
        [Column("Фамилия автора")]
        public string Фамилияавтора { get; set; }
        [Column("Отчество автора")]
        public string Отчествоавтора { get; set; }
        public string Группа { get; set; }
        [Column("Название издательства")]
        public string Названиеиздательства { get; set; }
        [Column("Страна издательства")]
        public string Странаиздательства { get; set; }
    }
}
