// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryWin.Models
{
    public partial class GetEmpInTheHallResult
    {
        [Column("ID сотрудника")]
        public int IDсотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public string Должность { get; set; }
        public decimal Зарплата { get; set; }
        [Column("Номер зала")]
        public string Номерзала { get; set; }
        [Column("Тип зала")]
        public string Типзала { get; set; }
    }
}
