// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Hall
{
    public int HallId { get; set; }

    public int? DepartmentOfIssanceId { get; set; }

    public string Number { get; set; }

    public int MaximumNumberOfvisitors { get; set; }

    public string Type { get; set; }

    public virtual DepartmentOfIssuance DepartmentOfIssance { get; set; }

    public virtual ICollection<HallEmployee> HallEmployees { get; set; } = new List<HallEmployee>();

    public virtual ICollection<Rack> Racks { get; set; } = new List<Rack>();
}