// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LibraryWin.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LibraryWin.Models
{
    public partial interface ILibraryDBContextProcedures
    {
        Task<List<getBookInfoResult>> getBookInfoAsync(string nameBook, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getBookPositionResult>> getBookPositionAsync(string nameBook, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetEmpInTheHallResult>> GetEmpInTheHallAsync(int? EmpID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
