// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Librarian
{
    public int LibrarianId { get; set; }

    public int DepartmentOfIssuanceId { get; set; }

    public string FirstName { get; set; }

    public string Surname { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual ICollection<BookIssuance> BookIssuances { get; set; } = new List<BookIssuance>();

    public virtual DepartmentOfIssuance DepartmentOfIssuance { get; set; }
}