// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using LibraryWin.Models;

namespace LibraryWin.Models
{
    public partial class LibraryDBContext
    {

        [DbFunction("HallEmpCount", "dbo")]
        public static int? HallEmpCount(int? empID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("postSalaryMax", "dbo")]
        public static int? postSalaryMax(string postName)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
