// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class PostInfo
{
    public string Должность { get; set; }

    public decimal? СредняяЗарплата { get; set; }

    public decimal? МинимальнаяЗарплата { get; set; }

    public decimal? МаксимальнаяЗарплата { get; set; }

    public decimal? СуммаЗарплат { get; set; }
}