// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Rack
{
    public int RackId { get; set; }

    public int HallId { get; set; }

    public string RackNumber { get; set; }

    public int NumberOfShelves { get; set; }

    public int MaximumNumberOfBooks { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    public virtual Hall Hall { get; set; }

    public virtual ICollection<RecycledBook> RecycledBooks { get; set; } = new List<RecycledBook>();
}