// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class Reader
{
    public int ReaderId { get; set; }

    public string LastName { get; set; }

    public string SurName { get; set; }

    public string FirstName { get; set; }

    public decimal? Fine { get; set; }

    public virtual ICollection<BookIssuance> BookIssuances { get; set; } = new List<BookIssuance>();
}