// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryWin.Models;

public partial class RecycledBook
{
    public int RecycledBookId { get; set; }

    public int RackId { get; set; }

    public string PublishingHouse { get; set; }

    public string AuthorFirstName { get; set; }

    public string AuthorSurName { get; set; }

    public string AuthorLastName { get; set; }

    public int NumberOfPages { get; set; }

    public string Isbn { get; set; }

    public string Name { get; set; }

    public int CodeBook { get; set; }

    public virtual Rack Rack { get; set; }
}